
require("dotenv").config();
const express = require("express");


const session = require("express-session");
const MongoStore = require("connect-mongo");
const bcrypt = require("bcrypt");
const saltRounds = 12;
const nodemailer = require('nodemailer');
const cloudinary = require('cloudinary').v2;
const multer = require('multer');
const { CloudinaryStorage } = require('multer-storage-cloudinary');
const MongoClient = require("mongodb").MongoClient;
const Joi = require("joi");
const path = require('path');
const {v4: uuid} = require('uuid');
const streamifier = require('streamifier');
const bodyParser = require('body-parser');
const port = process.env.PORT || 3000;
const app = express();

app.use(express.static(__dirname + '/public'));

// Middleware to parse URL-encoded bodies (for form submissions)
app.use(bodyParser.urlencoded({ extended: true }));

// Middleware to parse JSON bodies
app.use(bodyParser.json());


const expireTime = 60 * 60 * 1000;

/* Secret information section */
const mongodb_host = process.env.MONGODB_HOST;
const mongodb_user = process.env.MONGODB_USER;
const mongodb_password = process.env.MONGODB_PASSWORD;
const mongodb_database = process.env.MONGODB_DATABASE;
const mongodb_session_secret = process.env.MONGODB_SESSION_SECRET;
const node_session_secret = process.env.MONGODB_SESSION_SECRET;

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_CLOUD_KEY,
  api_secret: process.env.CLOUDINARY_CLOUD_SECRET,
});

// code referenced from https://www.youtube.com/watch?v=3Gj_mL9JJ6k
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: 'uploads',
    resource_type: 'auto',
    allowedFormats: ['jpg', 'png', 'jpeg'],
  },
});
const upload = multer({ storage: storage });
const uploadNone = multer();

// Setting up a connection to MongoDB database
// code referenced from COMP2537 assignment 2
const atlasURI = `mongodb+srv://${mongodb_user}:${mongodb_password}@${mongodb_host}/${mongodb_database}`;
var database = new MongoClient(atlasURI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Connect to the database
// code referenced from COMP2537 assignment 2
database.connect((err) => {
  if (err) throw err;
  console.log("Connected to MongoDB!");
});

// create a new session store
// code referenced from COMP2537 assignment 2
const mongoStore = MongoStore.create({
  mongoUrl: atlasURI,
  crypto: {
    secret: mongodb_session_secret,
  },
});

// sets the view engine to ejs
// code referenced from COMP2537 assignment 2
app.set('view engine', 'ejs');

const userCollection = database.db(mongodb_database).collection("users");
const capsuleCollection = database.db(mongodb_database).collection("capsule");
const { ObjectId } = require('mongodb');

// Middleware to add session object to all requests
// code referenced from COMP2537 assignment 2
app.use(
  session({
    secret: node_session_secret,
    store: mongoStore,
    saveUninitialized: false,
    resave: true,
  })
);

/* Get Current date
 Generated by ChatGPT 4.0
@ author chat.openai.com */
function getCurrentDate() {
  const currentDate = new Date();
  const date = currentDate.toISOString().split('T')[0];

  return date;
}

/* Set up email transporter
source: https://medium.com/@y.mehnati_49486/how-to-send-an-email-from-your-gmail-account-with-nodemailer-837bf09a7628 */
const transporter = nodemailer.createTransport({
  service: "Gmail",
  host: "smtp.gmail.com",
  port: 465,
  secure: true,
  auth: {
    user: process.env.NODEMAILER_EMAIL,
    pass: process.env.NODEMAILER_PASSWORD,
  },
});

/* Unlock Capsule
Generated by ChatGPT 4.0 and copilot
@ author chat.openai.com & github.com/copilot */
async function unlockCapsule() {
  const currentDate = getCurrentDate();
  
  const result = await capsuleCollection.find({ lockedUntil: { $lte: currentDate } }).project({user_id: 1, title: 1}).toArray();

  console.log(result);
try {
  if (result.length == 0) {
    console.log("No capsules to unlock");
    return;
  } else {
    
    const capsuleNames = result.map(item => item.title);
    console.log("Capsules to unlock: ", capsuleNames);
    const userIDs = result[0].user_id;
    console.log("User IDs: ", userIDs);
    const userObjectID = new ObjectId(userIDs);
        
    const user = await userCollection.find({ _id: userObjectID }).project({ name: 1, email: 1 }).toArray();

    result.forEach(async (item) => {
      console.log("Unlocking Capsule ====> "+ item.title);
      await capsuleCollection.updateOne({ _id: item._id }, { $set: { lock: false, lockedUntil: null } });
    });

    let info = await transporter.sendMail({
      from: process.env.NODEMAILER_EMAIL, // sender address
      to: user[0].email, // list of receivers
      subject: "NoReply - Memory Lane: Capsule Unlocked", // Subject line
      html: `<h2>Hello ${user[0].name}, your capsule ${capsuleNames} has been unlocked.<h2></br>
      <p><a href="https://two800-202410-bby17-q3pp.onrender.com">Click here</a> to sign in</p>
      <footer><p>Memory Lane Team</p></footer>`, // html body
    });
    console.log("Message sent: %s", info.messageId);

    }
  } catch (err) {
    console.error("Error unlocking capsule:", err);
  }
}

//Scheduler set up
const schedule = require('node-schedule');
const { profile } = require("console");

// unlock capsule every ... seconds/mins/hours/days/months/years
// source: https://www.youtube.com/watch?v=Ezv30i47sDs
const job = schedule.scheduleJob('*/10 * * * * *', () => {
  console.log('Running unlockCapsule job');
  unlockCapsule();
});

function isValidSession(req) {
  if (req.session.authenticated) {
    return true;
  }
  return false;
}

function sessionValidation(req, res, next) {
  if (isValidSession(req)) {
    next();
  }
  else {
    res.redirect('/');
  }
}

function adminAuthorization(req, res, next) {
  if (req.session.user_type === 'admin') {
    next();
  } else {
    res.status(403);
    res.render("errorMessage", { error: "Not Authorized" });
  }
}

app.use((req, res, next) => {
  res.locals.isLoggedIn = req.session.authenticated;
  next();
});

app.get("/", (req, res) => {
  res.render("index");
});

app.get("/nosql-injection", async (req, res) => {
  const username = req.query.user;

  if (!username) {
    res.send(
      `<h3>No user provided - try /nosql-injection?user=name or /nosql-injection?user[$ne]=name</h3>`
    );
    return;
  }

  const schema = Joi.string().max(20).required();
  const validationResult = schema.validate(username);

  if (validationResult.error != null) {
    res.send("<h1 style='color:darkred;'>A NoSQL injection attack was detected!!</h1>");
    return;
  }

  const result = await userCollection
    .find({ username: username })
    .project({ username: 1, password: 1, _id: 1 })
    .toArray();

  res.send(`<h1>Hello ${username}</h1>`);
});
/**
 * I used the code of my web dev assignment-2
 */
app.post("/submitUser", async (req, res) => {
  const { name, email, password } = req.body;

  if (!name || !email || !password) {
    return res.send("Name, email, and password are required. <a href='/'>Try again</a>");
  }

  const schema = Joi.object({
    name: Joi.string().max(30).required(),
    email: Joi.string().email({ minDomainSegments: 2, tlds: { allow: ["com", "net", "ca"] } }).required(),
    password: Joi.string().min(3).max(50).required(),
  });

  const { error } = schema.validate({ name, email, password });

  if (error) {
    return res.render("index", { error: error.details[0].message });
  }

  const hashedPassword = await bcrypt.hash(password, saltRounds);

  const result = await userCollection.insertOne({ name, email, password: hashedPassword });

  req.session.authenticated = true;
  req.session.email = email;
  req.session.name = name;
  req.session.cookie.maxAge = expireTime;
  req.session.user_id = result.insertedId;

  return res.redirect("/members");
});

app.get("/loginSignUp", (req, res) => {
  res.render("loginSignUp");
})

app.post("/loggingin", async (req, res) => {
  const email = req.body.email;
  const password = req.body.password;

  const schema = Joi.string().email().required();
  const validationResult = schema.validate(email);
  if (validationResult.error != null) {
    return res.send(`Invalid email/password combination. <a href="/">Try again</a>`);
  }

  const result = await userCollection
    .find({ email: email })
    .project({ email: 1, name: 1, password: 1, _id: 1 })
    .toArray();

  if (result.length != 1) {
    return res.send(`Invalid email/password combination. <a href="/">Try again</a>`);
  }

  if (await bcrypt.compare(password, result[0].password)) {
    req.session.authenticated = true;
    req.session.email = result[0].email;
    req.session.name = result[0].name;
    req.session.cookie.maxAge = expireTime;
    req.session.user_id = result[0]._id;
    return res.redirect("/loggedin");
  } else {
    return res.send(`Invalid email/password combination. <a href="/">Try again</a>`);
  }
});

app.get("/loginsignup", (req, res) => {
  res.render("loginsignup");
});

app.get("/loggedin", async (req, res) => {
  if (!req.session.authenticated) {
    return res.redirect("/");
  }

  res.redirect("/members");
});

app.get('/members', sessionValidation, async (req, res) => {
  try {
    
    const authenticated = req.session.authenticated;
    const username = req.session.name;
    const email = req.session.email;

    // Find the user's capsules
    const capsules = await capsuleCollection.find({ user_id: req.session.user_id }).project({
      title: 1,
      date: 1,
      images: 1,
      user_id: 1,
      lock: 1,
      lockedUntil: 1
    }).toArray();

    // Find the user document
    const user = await userCollection.findOne({ _id: new ObjectId(req.session.user_id) });

    if (!user) {
      return res.status(404).send("User not found");
    }

    const friends = user.friends || [];
    const profileImage = user.ProfileImage || 'default.jpg';
    const backgroundImage = user.BGImage || 'background.jpg';
    const userbio = user.bio || 'About me'

    
    console.log(user);
    console.log(capsules);

    // Convert ObjectIds to strings
    capsules.forEach((element) => {
      element._id = element._id.toString();
    });

    
    res.render('members', { authenticated, username, email, capsules, friends,  profileImage, backgroundImage, userbio});
  } catch (error) {
    console.error("Error fetching user data:", error);
    res.status(500).send("Error fetching user data.");
  }
});

// Destroy the session and redirect to the home page
// code referenced from COMP2537 assignment 2
app.get("/logout", (req, res) => {
  req.session.destroy();
  res.redirect("/");
});

app.get('/createCapsule', sessionValidation, (req, res) => {
  res.render('createCapsule');
});


app.post('/deletemessage', sessionValidation, async (req, res) => {
  delete req.session.message;
  res.json({ message: "Message deleted" });
} );


// code referenced from https://www.youtube.com/watch?v=3Gj_mL9JJ6k
//  handle image uploads
app.post('/upload', upload.array('images'), async (req, res) => {
  try {
    const { title, date, 'capsule-caption': capsuleCaption } = req.body;
    const user_id = req.session.user_id;
    const sections = req.body.sections || [];
    const captionsArray = req.body.captions || [];
    const imageOrdering = req.body.ordering || [];
    const images = req.files.map((file, index) => {
      const caption = captionsArray[index] || '';
      const order = imageOrdering[index] || 1;
      return {
        path: file.path,
        caption: caption,
        order: order,
        type: file.mimetype
      };
    });

    const newCapsule = {
      title: title,  // Title of the capsule
      date: date,    // Date associated with the capsule
      images: images,  // Array of image paths
      capsuleCaption: capsuleCaption,
      sections: sections,
      user_id: user_id,  // ID of the user who uploaded the capsule
      lock: false
    };
    await capsuleCollection.insertOne(newCapsule);

    res.json({ message: "Upload successful" });
  } catch (error) {
    res.status(500).json({ message: "Upload failed" });
  }
});


app.get('/openCapsule', sessionValidation, async (req, res) => {
  //TODO: validate open date before giving user access
  let capsuleID = req.query.id;
  //let capsuleID = new ObjectId("664787f4206421c9ebdb8fc1");
  objID = new ObjectId(capsuleID);
  const result = await capsuleCollection.find({ _id: objID })
    .project({ title: 1, date: 1, images: 1, user_id: 1, capsuleCaption: 1, sections: 1 }).toArray();

  if (result.length != 1) {
    console.log("Capsule not found");
    //res.redirect('?invalid=1');
  } else {
    res.render('openCapsule', { data: result });
  }
});

app.get("/forgotPassword", (req, res) => {
  res.render("forgotPassword");
});

function generateToken() {
  const randomNum = Math.random() * 9000
  return Math.floor(1000 + randomNum)
};

app.post("/sendOTP", async (req, res) => {
  var email = req.body.email;
  const schema = Joi.string().email().required();
  const validationResult = schema.validate(email);
  if (validationResult.error != null) {
    console.log("hi");
    var html = `Invalid email/password combination.
                <a href="/">Try again</a>
    `;
    res.send(html);
    return;
  }

  const result = await userCollection
    .find({ email: email })
    .project({ email: 1, username: 1, password: 1, _id: 1 })
    .toArray();

  console.log(result);
  if (result.length != 1) {
    console.log("user not found");
    var html = `Invalid email/password combination.
                <a href="/">Try again</a>
    `;
    res.send(html);
    // res.redirect("/login");
    return;
  }
  else {
    console.log("User is present");
    var OTP = generateToken();

    await userCollection.updateOne(
      { email: email },
      { $set: { OTP: OTP } }
    );
    console.log("OTP generated ");

    let info = await transporter.sendMail({
      from: process.env.NODEMAILER_EMAIL, // sender address
      to: email, // list of receivers
      subject: "OTP for login", // Subject line
      text: `Hello, <br>Your OTP to reset password for 'MemoryLane' is ${OTP}.`, // plain text body
      html: `Hello, <br>Your OTP to reset password for 'MemoryLane' is <b>${OTP}</b>.<br> Thanks`, // html body
    });

    console.log("Message sent: %s", info.messageId);
    res.redirect("/enterOTP");
  }
});

app.get("/enterOTP", (req, res) => {
  res.render("enterOTP");
});

app.post("/validateOTP", async (req, res) => {
  try {
    const OTP = req.body.OTP;

    console.log("Received OTP:", OTP);

    const result = await userCollection.find({ OTP: OTP })
      .project({ email: 1, username: 1, password: 1, _id: 1, OTP: 1 })
      .toArray();

    console.log("Query result:", result); // Log the query result

    if (result) {
      // If a user with the OTP is found, consider it as a valid OTP
      console.log("OTP is valid");
      res.redirect("/resetPassword/" + OTP);
    } else {
      // If no user with the OTP is found, consider it as invalid
      console.log("Invalid OTP");
      res.status(400).send("Invalid OTP");
    }
  } catch (error) {
    // Handle any errors that occur during the process
    console.error("Error validating OTP:", error);
    res.status(500).send("Internal Server Error");
  }
});

app.get("/resetPassword/:OTP", (req, res) => {
  var OTP = req.params.OTP;
  res.render("resetPassword", { OTP: OTP });
});

app.post("/resetPassword/:OTP", async (req, res) => {
  const OTP = parseInt(req.params.OTP, 10); // Convert OTP to integer
  const newPassword = req.body.newPassword;

  try {
    // Hash the new password
    const hashedPassword = await bcrypt.hash(newPassword, saltRounds);

    // Update the password in the database
    const result = await userCollection.updateOne(
      { OTP: OTP },
      { $set: { password: hashedPassword } }
    );

    console.log(result);

    // Redirect the user to the login/signup page
    res.redirect('/loginSignUp');
  } catch (err) {
    console.error("Error updating password:", err);

    // Render an error page if something goes wrong
    res.status(500).render('error', { error: "Server error. Please try again later." });
  }
});

//Lock/unlock Capsule Feature
//Generated by ChatGPT 4.0 and Copilot
//@auhtor chat.openai.com & github.com/copilot
app.post('/lockUnlockCapsule', sessionValidation, async (req, res) => {
  console.log("Locking Capsule");
  const lockedUntil = new Date(req.body.lockedUntil);
  const date = lockedUntil.getDate() + 1;
  const month = lockedUntil.getMonth() + 1;
  const year = lockedUntil.getFullYear();

  const formattedDate = `${year}-${month.toString().padStart(2, '0')}-${date.toString().padStart(2, '0')}`;
  console.log(formattedDate);
  const capsuleID = req.query.id;
  const objID = new ObjectId(capsuleID);
  let result = await capsuleCollection.find({_id: objID}).project({title: 1, date: 1, images: 1, user_id: 1, lock: 1}).toArray();
  console.log("Lock Status:" + result[0].lock);
  
try {
  
  if (result[0].lock == true) {
    result = await capsuleCollection.updateOne({_id: objID}, {$set: {lock: false, lockedUntil: null}});
    console.log("Capsule unlocked");

    res.redirect('/members');
    
    return;
  } else {
    result = await capsuleCollection.updateOne({_id: objID}, {$set: {lock: true, lockedUntil: formattedDate}});
    console.log("Capsule locked");

    res.redirect('/members');

    return
  }
} catch (err) {
  console.error("Error locking capsule:", err);

  try {
    if (result[0].lock == true) {
      result = await capsuleCollection.updateOne({ _id: objID }, { $set: { lock: false, lockedUntil: null } });
      console.log("Capsule unlocked");
      res.redirect('/members');
      return;
    } else {
      result = await capsuleCollection.updateOne({ _id: objID }, { $set: { lock: true, lockedUntil: formattedDate } });
      console.log("Capsule locked");
      res.redirect('/members');
    }
  } catch (err) {
    console.error("Error locking capsule:", err);

    // Render an error page if something goes wrong
    res.status(500).render('error', { error: "Server error. Please try again later." });
  }
}
});

// Serve static files from directory "public"
// code referenced from COMP2537 assignment 2
app.use(express.static(__dirname + '/public'));

app.use(express.static(__dirname + "/images"));

app.get('/friends', sessionValidation, async (req, res) => {
  try {
    const allUsers = await userCollection.find({ _id: { $ne: ObjectId.createFromHexString(req.session.user_id) } }).toArray();

    const currentUser = await userCollection.findOne({ _id: ObjectId.createFromHexString(req.session.user_id) });

    if (!currentUser) {
      console.error("Current user not found in the database.");
      res.status(500).render('error', { error: "Current user not found." });
      return;
    }

    const friendsIds = currentUser.friends || [];

    const friends = [];
    console.log("Friends IDs before processing:", friendsIds);
    for (const friendId of friendsIds) {
      console.log("Processing friend ID:", friendId);

      const processedFriendId = friendId instanceof ObjectId ? friendId : ObjectId.isValid(friendId) ? friendId : null;
      if (processedFriendId) {
        try {
          const friend = await userCollection.findOne({ _id: processedFriendId }, { projection: { name: 1, email: 1 } });
          console.log("Friend Details:", friend);
          if (friend) {
            friends.push(friend);
          }
        } catch (error) {
          console.error("Error fetching friend details:", error);
        }
      } else {
        console.error("Invalid friend ID:", friendId);
      }
    }
    console.log("Friends:", friends);

    const usersToAdd = allUsers.filter(user => !friends.some(friend => friend._id.equals(user._id)));

    res.render('friends', {
      username: req.session.name,
      email: req.session.email,
      allUsers: usersToAdd,
      friends: friends
    });
  } catch (error) {
    console.error("Error fetching users or friends:", error);
    res.status(500).render('error', { error: "Server error. Please try again later." });
  }
});

app.post("/addFriend/:userId", sessionValidation, async (req, res) => {
  try {
    const userId = req.params.userId;
    console.log("User ID:", userId);
    console.log("Session User ID:", req.session.user_id);

    const currentUser = await userCollection.findOne({ _id: ObjectId.createFromHexString(req.session.user_id) });
    console.log("Current User:", currentUser);

    const user = await userCollection.findOne({ _id: ObjectId.createFromHexString(userId) });
    console.log("User found:", user);

    if (!user) {
      console.log("User not found");
      res.status(404).render('error', { error: "User not found." });
      return;
    }

    await userCollection.updateOne(
      { _id: ObjectId.createFromHexString(req.session.user_id) },
      { $push: { friends: ObjectId.createFromHexString(userId) } }
    );

    console.log("Friend added successfully");

    res.redirect("/friends");
  } catch (error) {
    console.error("Error adding friend:", error);
    res.status(500).render('error', { error: "Server error. Please try again later." });
  }
});

app.post("/removeFriend/:friendId", sessionValidation, async (req, res) => {
  try {
    const friendId = req.params.friendId;
    const userId = req.session.user_id;

    await userCollection.updateOne(
      { _id: ObjectId.createFromHexString(userId) },
      { $pull: { friends: ObjectId.createFromHexString(friendId) } }
    );

    console.log("Friend removed successfully");

    res.redirect("/friends");
  } catch (error) {
    console.error("Error removing friend:", error);
    res.status(500).render('error', { error: "Server error. Please try again later." });
  }
});
app.get('/editLanding', (req, res) => {
  
  res.render('editLanding'); 
});


app.get('/editProfile', (req, res) => {
  const userId = req.session.user_id;
  res.render('editProfile', { userId }); 
});

app.get('/editBG', (req, res) => {
  const userId = req.session.user_id;
  res.render('editBG', { userId }); 
});

app.get('/editBio', (req, res) => {
  const userId = req.session.user_id;
  const user = { bio: 'About yourself.' }; 
  res.render('editBio', { userId, user: user });
});


app.post("/editProPic", upload.single('image'), async (req, res) => {
  let imagePath;
  try {
    const { id } = req.body; 
    imagePath = req.file.path;

    console.log('Received request to update user ID:', id);
    console.log('Image path:', imagePath);

    const result = await userCollection.updateOne({ _id: new ObjectId(id) }, { $set: { ProfileImage: imagePath } });

    console.log('Update result:', result);

  } catch (error) {
    console.error("Error updating profile:", error);
    return res.status(500).send("Error updating profile.");
  }
  
  
  res.redirect('/members');
});

app.post("/editBackPic", upload.single('image'), async (req, res) => {
  let imagePath;
  try {
    const { id } = req.body; 
    imagePath = req.file.path;

    console.log('Received request to update user ID:', id);
    console.log('Image path:', imagePath);

    const result = await userCollection.updateOne({ _id: new ObjectId(id) }, { $set: { BGImage: imagePath } });

    console.log('Update result:', result);

  } catch (error) {
    console.error("Error updating profile:", error);
    return res.status(500).send("Error updating profile.");
  }
  
  
  res.redirect('/members');
});

app.post('/editAbout', uploadNone.none(), async (req, res) => {
  const userId = req.body.userId;
  const bio = req.body.bio;

  
  if (!userId || !bio) {
    return res.status(400).send('User ID and Bio are required.');
  }

  try {
    // Update the user's bio in your database
    const result = await userCollection.updateOne({ _id: new ObjectId(userId) }, { $set: { bio: bio } });
    console.log('Update result:', result);

    res.send('Bio updated successfully');
  } catch (error) {
    console.error('Error updating bio:', error);
    res.status(500).send('Internal server error');
  }
});


app.get("/profile", async (req, res) => {
  let friendId = req.query.id;
  console.log("this is profile page:" + friendId);

  try {
    let objectId = new ObjectId(friendId);

    let result = await capsuleCollection.find({ user_id: friendId })
      .project({ _id: 1, title: 1, date: 1, images: 1 })
      .toArray();

    let userData = await userCollection.findOne({ _id: objectId }, { projection: { name: 1, email: 1, ProfileImage: 1, image: 1 } });
    let username = userData ? userData.name : '';
    let email = userData ? userData.email : '';
    let profileImage = userData ? userData.ProfileImage : 'birthday.jpg';
    let image = userData ? userData.image : 'background.jpg';
    console.log(result);
    console.log(username);
    console.log(email);
    console.log("Profile Image URL: ", profileImage);

    res.render("profile", { result, username, email, profileImage, image });
  } catch (err) {
    console.error("Error fetching data:", err);
    res.status(500).send("Error fetching data");
  }
});

// route handler for get request that doesn't match any of the above
// code referenced from COMP2537 assignment 2
app.get("*", (req, res) => {
  res.status(404);
  res.render("error");
});

// creates a server that listens on port
// code referenced from COMP2537 assignment 2
app.listen(port, () => {
  console.log("Node application listening on port " + port);
});
